'use strict';

var OPEN_ESC_DEFAULTS = {
	'0': {
		MOTOR_DIRECTION: 0,
		BIDIRECTIONAL_MODE: 0,
		SINUSOIDAL_STARTUP: 0,
		COMPLEMENTARY_PWM: 1,
		VARIABLE_PWM_FREQUENCY: 1,
		STUCK_ROTOR_PROTECTION: 1,
		TIMING_ADVANCE: 2,
		PWM_FREQUENCY: 24,
		STARTUP_POWER: 100,
		MOTOR_KV: 55,
		MOTOR_POLES: 14,
		BRAKE_ON_STOP: 1,
		STALL_PROTECTION: 0,
	}
};
